nginx-ingress:
  controller: 
    service: 
      type: LoadBalancer

cert-manager:
  ingressShim:
    defaultIssuerName: letsencrypt-prod
    defaultIssuerKind: ClusterIssuer

email_id: akashkatakam1@gmail.com