apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 labels:
   name: letsencrypt-prod
 name: letsencrypt-prod
spec:
 acme:
   email: {{ .Values.email_id }}
   http01: {}
   privateKeySecretRef:
     name: letsencrypt-prod
   server: https://acme-staging-v02.api.letsencrypt.org/directory